/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Rent;


import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.JOptionPane;

import Registration.*;
import loginform.*;
import Hospital.*;
import Rent.*;
import Home.*;
import JDBC.DbConnection;
import Plan.myplan;





/**
 *
 * @author User
 */
public class Rent1 extends javax.swing.JFrame {

    /**
     * Creates new form background
     */
    //DefaultTableModel model,model1;
    
    
    public Rent1() {
        initComponents();
        
        //model=(DefaultTableModel)tblresult.getModel();
       // model1=(DefaultTableModel) tblsearch.getModel();
       // radioyes.setActionCommand("YES");
       // radiono.setActionCommand("NO");
       // thead();
       // jScrollPane5.getVerticalScrollBar().setUnitIncrement(20);
        
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnldashboard = new javax.swing.JPanel();
        lbllogo = new javax.swing.JLabel();
        lblsublogo = new javax.swing.JLabel();
        lblborder = new javax.swing.JLabel();
        pnlhome = new javax.swing.JPanel();
        iconhome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlhospital = new javax.swing.JPanel();
        iconhospitals = new javax.swing.JLabel();
        lblhospitals = new javax.swing.JLabel();
        pnlplan = new javax.swing.JPanel();
        iconplan = new javax.swing.JLabel();
        lblplan = new javax.swing.JLabel();
        pnlregistration = new javax.swing.JPanel();
        iconregistration = new javax.swing.JLabel();
        lblregistration = new javax.swing.JLabel();
        pnllogout = new javax.swing.JPanel();
        iconlogout = new javax.swing.JLabel();
        lbllogout = new javax.swing.JLabel();
        pnlback = new javax.swing.JPanel();
        backicon = new javax.swing.JLabel();
        lblbottom = new javax.swing.JLabel();
        pnlforward = new javax.swing.JPanel();
        lblforward = new javax.swing.JLabel();
        pnlrent = new javax.swing.JPanel();
        iconrent1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        iconlogo = new javax.swing.JLabel();
        pnlhead = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        edate = new javax.swing.JTextField();
        sdate = new javax.swing.JTextField();
        eloc = new javax.swing.JTextField();
        sloc = new javax.swing.JTextField();
        sub = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        drop = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnldashboard.setBackground(new java.awt.Color(54, 33, 89));
        pnldashboard.setPreferredSize(new java.awt.Dimension(310, 600));

        lbllogo.setBackground(new java.awt.Color(25, 151, 148));
        lbllogo.setFont(new java.awt.Font("Source Code Pro Black", 1, 28)); // NOI18N
        lbllogo.setForeground(new java.awt.Color(255, 255, 255));
        lbllogo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbllogo.setText("HOLIDAY HELPER...");

        lblsublogo.setBackground(new java.awt.Color(25, 151, 148));
        lblsublogo.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 18)); // NOI18N
        lblsublogo.setForeground(new java.awt.Color(255, 255, 255));
        lblsublogo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblsublogo.setText("--FLY SRILANKA--");

        lblborder.setBackground(new java.awt.Color(255, 255, 255));
        lblborder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblborder.setPreferredSize(new java.awt.Dimension(2, 2));

        pnlhome.setBackground(new java.awt.Color(85, 65, 118));
        pnlhome.setForeground(new java.awt.Color(255, 255, 255));
        pnlhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlhomeMouseClicked(evt);
            }
        });
        pnlhome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconhome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        pnlhome.add(iconhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 50));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Home");
        pnlhome.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 170, 30));

        pnlhospital.setBackground(new java.awt.Color(64, 43, 100));
        pnlhospital.setForeground(new java.awt.Color(255, 255, 255));
        pnlhospital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlhospitalMouseClicked(evt);
            }
        });
        pnlhospital.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconhospitals.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconhospitals.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hospitals.png"))); // NOI18N
        pnlhospital.add(iconhospitals, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 50));

        lblhospitals.setBackground(new java.awt.Color(255, 255, 255));
        lblhospitals.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblhospitals.setForeground(new java.awt.Color(255, 255, 255));
        lblhospitals.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblhospitals.setText("Hospitals");
        pnlhospital.add(lblhospitals, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 170, 30));

        pnlplan.setBackground(new java.awt.Color(64, 43, 100));
        pnlplan.setForeground(new java.awt.Color(255, 255, 255));
        pnlplan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlplanMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlplanMousePressed(evt);
            }
        });
        pnlplan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconplan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconplan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plan.png"))); // NOI18N
        pnlplan.add(iconplan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 40));

        lblplan.setBackground(new java.awt.Color(255, 255, 255));
        lblplan.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblplan.setForeground(new java.awt.Color(255, 255, 255));
        lblplan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblplan.setText("Make My Plan");
        pnlplan.add(lblplan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 170, 30));

        pnlregistration.setBackground(new java.awt.Color(64, 43, 100));
        pnlregistration.setForeground(new java.awt.Color(255, 255, 255));
        pnlregistration.setPreferredSize(new java.awt.Dimension(270, 50));
        pnlregistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlregistrationMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlregistrationMousePressed(evt);
            }
        });
        pnlregistration.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconregistration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconregistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/registration.png"))); // NOI18N
        pnlregistration.add(iconregistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 30));

        lblregistration.setBackground(new java.awt.Color(255, 255, 255));
        lblregistration.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblregistration.setForeground(new java.awt.Color(255, 255, 255));
        lblregistration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblregistration.setText("Registration");
        pnlregistration.add(lblregistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 170, 20));

        pnllogout.setBackground(new java.awt.Color(64, 43, 100));
        pnllogout.setForeground(new java.awt.Color(255, 255, 255));
        pnllogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnllogoutMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnllogoutMousePressed(evt);
            }
        });
        pnllogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconlogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        pnllogout.add(iconlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 40));

        lbllogout.setBackground(new java.awt.Color(255, 255, 255));
        lbllogout.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbllogout.setForeground(new java.awt.Color(255, 255, 255));
        lbllogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllogout.setText("Log Out");
        lbllogout.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnllogout.add(lbllogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 170, 30));

        pnlback.setBackground(new java.awt.Color(64, 43, 100));
        pnlback.setForeground(new java.awt.Color(255, 255, 255));
        pnlback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlbackMousePressed(evt);
            }
        });
        pnlback.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backicon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.png"))); // NOI18N
        pnlback.add(backicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 50));
        backicon.getAccessibleContext().setAccessibleParent(this);

        lblbottom.setBackground(new java.awt.Color(255, 255, 255));
        lblbottom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblbottom.setPreferredSize(new java.awt.Dimension(2, 2));

        pnlforward.setBackground(new java.awt.Color(64, 43, 100));
        pnlforward.setForeground(new java.awt.Color(255, 255, 255));
        pnlforward.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlforwardMousePressed(evt);
            }
        });
        pnlforward.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblforward.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblforward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/forward.png"))); // NOI18N
        pnlforward.add(lblforward, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 50));

        pnlrent.setBackground(new java.awt.Color(64, 43, 100));
        pnlrent.setForeground(new java.awt.Color(255, 255, 255));
        pnlrent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconrent1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconrent1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rent.png"))); // NOI18N
        pnlrent.add(iconrent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 40));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Rent Vehicles");
        pnlrent.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 170, 30));

        iconlogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/travel.png"))); // NOI18N

        javax.swing.GroupLayout pnldashboardLayout = new javax.swing.GroupLayout(pnldashboard);
        pnldashboard.setLayout(pnldashboardLayout);
        pnldashboardLayout.setHorizontalGroup(
            pnldashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlhome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlhospital, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnllogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlplan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlregistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlrent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnldashboardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblsublogo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(pnldashboardLayout.createSequentialGroup()
                .addGroup(pnldashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnldashboardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnldashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbllogo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblbottom, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnldashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlback, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlforward, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnldashboardLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblborder, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnldashboardLayout.setVerticalGroup(
            pnldashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbllogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblsublogo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblborder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(pnlhome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(pnlhospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(pnlrent, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(pnlregistration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(pnlplan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnllogout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(pnldashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlback, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlforward, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblbottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlhead.setBackground(new java.awt.Color(160, 161, 194));
        pnlhead.setPreferredSize(new java.awt.Dimension(1240, 170));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Rent a Vehicle");

        javax.swing.GroupLayout pnlheadLayout = new javax.swing.GroupLayout(pnlhead);
        pnlhead.setLayout(pnlheadLayout);
        pnlheadLayout.setHorizontalGroup(
            pnlheadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlheadLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlheadLayout.setVerticalGroup(
            pnlheadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlheadLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Customer ID");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Vehicle Model");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Start Dtae");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("End Date ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Start location");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("End Location");

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        edate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edateActionPerformed(evt);
            }
        });

        sdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdateActionPerformed(evt);
            }
        });

        eloc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elocActionPerformed(evt);
            }
        });

        sloc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slocActionPerformed(evt);
            }
        });

        sub.setText("Booking");
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        drop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CAR", "BIKE", "PRADO", "THREEWHEEL" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(id)
                            .addComponent(drop, 0, 205, Short.MAX_VALUE)
                            .addComponent(sdate)
                            .addComponent(edate)
                            .addComponent(sloc)
                            .addComponent(eloc)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(377, 377, 377)
                        .addComponent(sub)
                        .addGap(48, 48, 48)
                        .addComponent(jButton2)))
                .addContainerGap(769, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sloc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eloc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(226, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnldashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlhead, javax.swing.GroupLayout.DEFAULT_SIZE, 1340, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnldashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlhead, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnlhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlhomeMouseClicked
        // TODO add your handling code here:
         Homepg H = new Homepg();
                H.setVisible(true);
                setVisible(false);
        
    }//GEN-LAST:event_pnlhomeMouseClicked

    private void pnlhospitalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlhospitalMouseClicked
        // TODO add your handling code here:
        myplan1 obj = new myplan1();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_pnlhospitalMouseClicked

    private void pnlplanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlplanMousePressed
        // TODO add your handling code here:
        resetColor(pnlhome);
        resetColor(pnlback);
        resetColor(pnlforward);
        resetColor(pnlhospital);
        resetColor(pnllogout);
        resetColor(pnlregistration);
        resetColor(pnlplan);
        setColor(pnlplan);
         resetColor(pnlrent);
    }//GEN-LAST:event_pnlplanMousePressed

    private void pnlregistrationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlregistrationMousePressed
        // TODO add your handling code here:
        resetColor(pnlhome);
        resetColor(pnlback);
        resetColor(pnlforward);
        resetColor(pnlhospital);
        resetColor(pnllogout);
        setColor(pnlregistration);
        resetColor(pnlplan);
        resetColor(pnlrent);
        
       // frameplan.setVisible(true);
    }//GEN-LAST:event_pnlregistrationMousePressed

    private void pnllogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnllogoutMousePressed
        // TODO add your handling code here:
        resetColor(pnlhome);
        resetColor(pnlback);
        resetColor(pnlforward);
        resetColor(pnlhospital);
        setColor(pnllogout);
        resetColor(pnlregistration);
        resetColor(pnlplan);
        resetColor(pnlrent);
    }//GEN-LAST:event_pnllogoutMousePressed

    private void pnlbackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlbackMousePressed
        // TODO add your handling code here:
        resetColor(pnlhome);
        setColor(pnlback);
        resetColor(pnlforward);
        resetColor(pnlhospital);
        resetColor(pnllogout);
        resetColor(pnlregistration);
        resetColor(pnlplan);
        resetColor(pnlrent);
    }//GEN-LAST:event_pnlbackMousePressed

    private void pnlforwardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlforwardMousePressed
        // TODO add your handling code here:
        resetColor(pnlhome);
        resetColor(pnlback);
        setColor(pnlforward);
        resetColor(pnlhospital);
        resetColor(pnllogout);
        resetColor(pnlregistration);
        resetColor(pnlplan);
        resetColor(pnlrent);
    }//GEN-LAST:event_pnlforwardMousePressed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnnextActionPerformed

    private void txtcalanderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcalanderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcalanderMouseClicked

    private void txtcalanderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcalanderKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcalanderKeyPressed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void edateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edateActionPerformed

    private void sdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sdateActionPerformed

    private void elocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elocActionPerformed

    private void slocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_slocActionPerformed

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed
       
            DbConnection l = new DbConnection();
            
        try {
            
            
            
            Class.forName(l.getDrive_class());
        } catch (ClassNotFoundException ex) {
            System.out.println("Error 01");
        }
        if(id.getText().isEmpty() || String.valueOf(drop.getSelectedItem() ).isEmpty() || sdate.getText().isEmpty() || edate.getText().isEmpty() || sloc.getText().isEmpty() || eloc.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Fill every field correctly!");
        }else{
            
            String s = id.getText();
            String a = String.valueOf(drop.getSelectedItem());
            String b = sdate.getText();
            String c = edate.getText();
            String d = sloc.getText();
            String e = eloc.getText();
            try {
                Connection conn = DriverManager.getConnection(l.getUrl(),l.getUsername(),l.getPassword());
                      String sql = "INSERT INTO vehical (customer_ID,V_Type ,Start_Date,End_Date,Start_Location,End_Location ) VALUES (?, ?, ?,?,?,?)";
                      PreparedStatement statement = conn.prepareStatement(sql);


                      statement.setString(1,s);
                      statement.setString(2,a );
                      statement.setString(3,b);
                      statement.setString(4,c);
                      statement.setString(5,d);
                      statement.setString(6,e);

                      int rowsInserted = statement.executeUpdate();

            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(null, "Successfull Booking!");
            } else {
                JOptionPane.showMessageDialog(null, "Update Unsuccessfully!");
            }
            }catch (SQLException ex) {
                Logger.getLogger(Rent1.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }   
       
                                                     // TODO add your handling code here:
    }//GEN-LAST:event_subActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);                 // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pnlregistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlregistrationMouseClicked
        // TODO add your handling code here:
        SignUp obj = new SignUp();
                obj.setVisible(true);
                setVisible(false);
    }//GEN-LAST:event_pnlregistrationMouseClicked

    private void pnlplanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlplanMouseClicked
        // TODO add your handling code here:
        myplan obj = new myplan();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_pnlplanMouseClicked

    private void pnllogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnllogoutMouseClicked
        // TODO add your handling code here:
         Login1 obj = new Login1();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_pnllogoutMouseClicked

    public void setColor(JPanel panel)
    {
        panel.setBackground(new Color(85,65,118));
        
    }
    public void resetColor(JPanel panel)
    {
        panel.setBackground(new Color(64,43,100));
    }
    
  
   

    
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        
        java.awt.EventQueue.invokeLater(() -> {
            new Rent1().setVisible(true);
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backicon;
    private javax.swing.JComboBox<String> drop;
    private javax.swing.JTextField edate;
    private javax.swing.JTextField eloc;
    private javax.swing.JLabel iconhome;
    private javax.swing.JLabel iconhospitals;
    private javax.swing.JLabel iconlogo;
    private javax.swing.JLabel iconlogout;
    private javax.swing.JLabel iconplan;
    private javax.swing.JLabel iconregistration;
    private javax.swing.JLabel iconrent1;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblborder;
    private javax.swing.JLabel lblbottom;
    private javax.swing.JLabel lblforward;
    private javax.swing.JLabel lblhospitals;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JLabel lbllogout;
    private javax.swing.JLabel lblplan;
    private javax.swing.JLabel lblregistration;
    private javax.swing.JLabel lblsublogo;
    private javax.swing.JPanel pnlback;
    private javax.swing.JPanel pnldashboard;
    private javax.swing.JPanel pnlforward;
    private javax.swing.JPanel pnlhead;
    private javax.swing.JPanel pnlhome;
    private javax.swing.JPanel pnlhospital;
    private javax.swing.JPanel pnllogout;
    private javax.swing.JPanel pnlplan;
    private javax.swing.JPanel pnlregistration;
    private javax.swing.JPanel pnlrent;
    private javax.swing.JTextField sdate;
    private javax.swing.JTextField sloc;
    private javax.swing.JButton sub;
    // End of variables declaration//GEN-END:variables
}
