/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home;

import java.awt.Color;
import javax.swing.JPanel;

import Registration.*;
import loginform.*;
import Plan.*;
import Hospital.*;
import Rent.*;
import java.awt.Desktop;
import java.net.URI;
import java.net.URL;





/**
 *
 * @author User
 */
public class Homepg extends javax.swing.JFrame {

    /**
     * Creates new form background
     */
    //DefaultTableModel model,model1;
    
    
    public Homepg() {
        initComponents();
        
        //model=(DefaultTableModel)tblresult.getModel();
       // model1=(DefaultTableModel) tblsearch.getModel();
       // radioyes.setActionCommand("YES");
       // radiono.setActionCommand("NO");
       // thead();
       // jScrollPane5.getVerticalScrollBar().setUnitIncrement(20);
        
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnldashboard = new javax.swing.JPanel();
        lbllogo = new javax.swing.JLabel();
        lblsublogo = new javax.swing.JLabel();
        lblborder = new javax.swing.JLabel();
        pnlhome = new javax.swing.JPanel();
        iconhome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlhospital = new javax.swing.JPanel();
        iconhospitals = new javax.swing.JLabel();
        lblhospitals = new javax.swing.JLabel();
        pnlplan = new javax.swing.JPanel();
        iconplan = new javax.swing.JLabel();
        lblplan = new javax.swing.JLabel();
        pnlregistration = new javax.swing.JPanel();
        iconregistration = new javax.swing.JLabel();
        lblregistration = new javax.swing.JLabel();
        pnllogout = new javax.swing.JPanel();
        iconlogout = new javax.swing.JLabel();
        lbllogout = new javax.swing.JLabel();
        pnlback = new javax.swing.JPanel();
        backicon = new javax.swing.JLabel();
        lblbottom = new javax.swing.JLabel();
        pnlforward = new javax.swing.JPanel();
        lblforward = new javax.swing.JLabel();
        pnlrent = new javax.swing.JPanel();
        iconrent1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        iconlogo = new javax.swing.JLabel();
        pnlhead = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnldashboard.setBackground(new java.awt.Color(54, 33, 89));
        pnldashboard.setPreferredSize(new java.awt.Dimension(310, 600));

        lbllogo.setBackground(new java.awt.Color(25, 151, 148));
        lbllogo.setFont(new java.awt.Font("Source Code Pro Black", 1, 28)); // NOI18N
        lbllogo.setForeground(new java.awt.Color(255, 255, 255));
        lbllogo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbllogo.setText("HOLIDAY HELPER...");

        lblsublogo.setBackground(new java.awt.Color(25, 151, 148));
        lblsublogo.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 18)); // NOI18N
        lblsublogo.setForeground(new java.awt.Color(255, 255, 255));
        lblsublogo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblsublogo.setText("--FLY SRILANKA--");

        lblborder.setBackground(new java.awt.Color(255, 255, 255));
        lblborder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblborder.setPreferredSize(new java.awt.Dimension(2, 2));

        pnlhome.setBackground(new java.awt.Color(85, 65, 118));
        pnlhome.setForeground(new java.awt.Color(255, 255, 255));
        pnlhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlhomeMouseClicked(evt);
            }
        });
        pnlhome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconhome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/Photos/home.png"))); // NOI18N
        pnlhome.add(iconhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 50));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Home");
        pnlhome.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 170, 30));

        pnlhospital.setBackground(new java.awt.Color(64, 43, 100));
        pnlhospital.setForeground(new java.awt.Color(255, 255, 255));
        pnlhospital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlhospitalMouseClicked(evt);
            }
        });
        pnlhospital.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconhospitals.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconhospitals.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/Photos/hospitals.png"))); // NOI18N
        pnlhospital.add(iconhospitals, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 50));

        lblhospitals.setBackground(new java.awt.Color(255, 255, 255));
        lblhospitals.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblhospitals.setForeground(new java.awt.Color(255, 255, 255));
        lblhospitals.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblhospitals.setText("Hospitals");
        pnlhospital.add(lblhospitals, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 170, 30));

        pnlplan.setBackground(new java.awt.Color(64, 43, 100));
        pnlplan.setForeground(new java.awt.Color(255, 255, 255));
        pnlplan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlplanMouseClicked(evt);
            }
        });
        pnlplan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconplan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconplan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/Photos/plan.png"))); // NOI18N
        pnlplan.add(iconplan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 40));

        lblplan.setBackground(new java.awt.Color(255, 255, 255));
        lblplan.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblplan.setForeground(new java.awt.Color(255, 255, 255));
        lblplan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblplan.setText("Make My Plan");
        pnlplan.add(lblplan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 170, 30));

        pnlregistration.setBackground(new java.awt.Color(64, 43, 100));
        pnlregistration.setForeground(new java.awt.Color(255, 255, 255));
        pnlregistration.setPreferredSize(new java.awt.Dimension(270, 50));
        pnlregistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlregistrationMouseClicked(evt);
            }
        });
        pnlregistration.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconregistration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconregistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/Photos/registration.png"))); // NOI18N
        pnlregistration.add(iconregistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 30));

        lblregistration.setBackground(new java.awt.Color(255, 255, 255));
        lblregistration.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblregistration.setForeground(new java.awt.Color(255, 255, 255));
        lblregistration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblregistration.setText("Registration");
        pnlregistration.add(lblregistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 170, 20));

        pnllogout.setBackground(new java.awt.Color(64, 43, 100));
        pnllogout.setForeground(new java.awt.Color(255, 255, 255));
        pnllogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnllogoutMouseClicked(evt);
            }
        });
        pnllogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconlogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/Photos/logout.png"))); // NOI18N
        pnllogout.add(iconlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 40));

        lbllogout.setBackground(new java.awt.Color(255, 255, 255));
        lbllogout.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbllogout.setForeground(new java.awt.Color(255, 255, 255));
        lbllogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllogout.setText("Log Out");
        lbllogout.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnllogout.add(lbllogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 170, 30));

        pnlback.setBackground(new java.awt.Color(64, 43, 100));
        pnlback.setForeground(new java.awt.Color(255, 255, 255));
        pnlback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlbackMousePressed(evt);
            }
        });
        pnlback.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backicon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/Photos/back.png"))); // NOI18N
        pnlback.add(backicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 50));
        backicon.getAccessibleContext().setAccessibleParent(this);

        lblbottom.setBackground(new java.awt.Color(255, 255, 255));
        lblbottom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblbottom.setPreferredSize(new java.awt.Dimension(2, 2));

        pnlforward.setBackground(new java.awt.Color(64, 43, 100));
        pnlforward.setForeground(new java.awt.Color(255, 255, 255));
        pnlforward.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlforwardMousePressed(evt);
            }
        });
        pnlforward.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblforward.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblforward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/Photos/forward.png"))); // NOI18N
        pnlforward.add(lblforward, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 60, 40));

        pnlrent.setBackground(new java.awt.Color(64, 43, 100));
        pnlrent.setForeground(new java.awt.Color(255, 255, 255));
        pnlrent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlrentMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlrentMousePressed(evt);
            }
        });
        pnlrent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconrent1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconrent1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/Photos/rent.png"))); // NOI18N
        pnlrent.add(iconrent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 40));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Rent Vehicles");
        pnlrent.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 170, 30));

        iconlogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/Photos/travel.png"))); // NOI18N

        javax.swing.GroupLayout pnldashboardLayout = new javax.swing.GroupLayout(pnldashboard);
        pnldashboard.setLayout(pnldashboardLayout);
        pnldashboardLayout.setHorizontalGroup(
            pnldashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlhospital, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnldashboardLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblborder, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(pnlrent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlhome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnldashboardLayout.createSequentialGroup()
                .addGroup(pnldashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlregistration, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnldashboardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnldashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnldashboardLayout.createSequentialGroup()
                                .addGroup(pnldashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbllogo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnldashboardLayout.createSequentialGroup()
                                        .addComponent(pnlback, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pnlforward, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(iconlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(pnlplan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnllogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnldashboardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblsublogo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(pnldashboardLayout.createSequentialGroup()
                .addComponent(lblbottom, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnldashboardLayout.setVerticalGroup(
            pnldashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbllogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblsublogo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblborder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlhome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlhospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlrent, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlregistration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlplan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnllogout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnldashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlback, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlforward, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblbottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2508, 2508, 2508))
        );

        pnlhead.setBackground(new java.awt.Color(51, 0, 102));
        pnlhead.setPreferredSize(new java.awt.Dimension(1240, 170));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("About Us");

        javax.swing.GroupLayout pnlheadLayout = new javax.swing.GroupLayout(pnlhead);
        pnlhead.setLayout(pnlheadLayout);
        pnlheadLayout.setHorizontalGroup(
            pnlheadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlheadLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 178, Short.MAX_VALUE))
        );
        pnlheadLayout.setVerticalGroup(
            pnlheadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlheadLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("For More Information......");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 250, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/Photos/Original.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 440, 430));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTextPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jTextPane1.setFont(new java.awt.Font("Papyrus", 1, 20)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(0, 51, 153));
        jTextPane1.setText("\n\"Our mission is to empower travelers to seam-lessly plan, organize, and enjoy their trips by providing a comprehensive and personalized trip planning platform. We aim to simplify the process of discovering destinations, creating itineraries, and making informed decisions, ulti-mately enhancing the travel experiences of our users. Through innovative features, curated recommendations, and a user-friendly inter-face, our goal is to be the go-to companion for travelers, enabling them to explore the world with confidence and convenience.\" ");
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnldashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(139, 139, 139))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlhead, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlhead, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pnldashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnlhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlhomeMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pnlhomeMouseClicked

    private void pnlhospitalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlhospitalMouseClicked
        // TODO add your handling code here:
        
        myplan1 obj = new myplan1();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_pnlhospitalMouseClicked

    private void pnlrentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlrentMousePressed
        // TODO add your handling code here:
        resetColor(pnlhome);
        resetColor(pnlback);
        resetColor(pnlforward);
        resetColor(pnlhospital);
        resetColor(pnllogout);
        resetColor(pnlregistration);
        resetColor(pnlplan);
        setColor(pnlrent);
    }//GEN-LAST:event_pnlrentMousePressed

    private void pnlbackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlbackMousePressed
        // TODO add your handling code here:
        resetColor(pnlhome);
        setColor(pnlback);
        resetColor(pnlforward);
        resetColor(pnlhospital);
        resetColor(pnllogout);
        resetColor(pnlregistration);
        resetColor(pnlplan);
        resetColor(pnlrent);
    }//GEN-LAST:event_pnlbackMousePressed

    private void pnlforwardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlforwardMousePressed
        // TODO add your handling code here:
        resetColor(pnlhome);
        resetColor(pnlback);
        setColor(pnlforward);
        resetColor(pnlhospital);
        resetColor(pnllogout);
        resetColor(pnlregistration);
        resetColor(pnlplan);
        resetColor(pnlrent);
    }//GEN-LAST:event_pnlforwardMousePressed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnnextActionPerformed

    private void txtcalanderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcalanderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcalanderMouseClicked

    private void txtcalanderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcalanderKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcalanderKeyPressed

    private void pnlregistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlregistrationMouseClicked
        // TODO add your handling code here:
        
                SignUp obj = new SignUp();
                obj.setVisible(true);
                setVisible(false);
        
    }//GEN-LAST:event_pnlregistrationMouseClicked

    private void pnlplanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlplanMouseClicked
        // TODO add your handling code here:
        
        myplan obj = new myplan();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_pnlplanMouseClicked

    private void pnllogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnllogoutMouseClicked
        // TODO add your handling code here:
        
        Login1 obj =new Login1();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_pnllogoutMouseClicked

    private void pnlrentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlrentMouseClicked
        // TODO add your handling code here:
        Rent1 obj = new Rent1();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_pnlrentMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        try{
            Desktop.getDesktop().browse(new URL("https://www.sltda.gov.lk/en").toURI());
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
        jLabel4.setForeground(new java.awt.Color(168, 185, 237));
    }//GEN-LAST:event_jLabel4MouseEntered

    public void setColor(JPanel panel)
    {
        panel.setBackground(new Color(85,65,118));
        
    }
    public void resetColor(JPanel panel)
    {
        panel.setBackground(new Color(64,43,100));
    }
    
  
   

    
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        
        java.awt.EventQueue.invokeLater(() -> {
            new Homepg().setVisible(true);
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backicon;
    private javax.swing.JLabel iconhome;
    private javax.swing.JLabel iconhospitals;
    private javax.swing.JLabel iconlogo;
    private javax.swing.JLabel iconlogout;
    private javax.swing.JLabel iconplan;
    private javax.swing.JLabel iconregistration;
    private javax.swing.JLabel iconrent1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblborder;
    private javax.swing.JLabel lblbottom;
    private javax.swing.JLabel lblforward;
    private javax.swing.JLabel lblhospitals;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JLabel lbllogout;
    private javax.swing.JLabel lblplan;
    private javax.swing.JLabel lblregistration;
    private javax.swing.JLabel lblsublogo;
    private javax.swing.JPanel pnlback;
    private javax.swing.JPanel pnldashboard;
    private javax.swing.JPanel pnlforward;
    private javax.swing.JPanel pnlhead;
    private javax.swing.JPanel pnlhome;
    private javax.swing.JPanel pnlhospital;
    private javax.swing.JPanel pnllogout;
    private javax.swing.JPanel pnlplan;
    private javax.swing.JPanel pnlregistration;
    private javax.swing.JPanel pnlrent;
    // End of variables declaration//GEN-END:variables
}
