/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hospital;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;

import Registration.*;
import loginform.*;
import Plan.*;

import Rent.*;
import Home.*;
import JDBC.DbConnection;






/**
 *
 * @author User
 */
public class myplan1 extends javax.swing.JFrame {

    

    /**
     * Creates new form background
     */
    //DefaultTableModel model,model1;
    
    
    public myplan1() {
        initComponents();
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setBorder(null);
        jScrollPane1.setViewportBorder(null);
        resultArea.setEditable(false);
        resultArea.setVisible(false);
        clearbt.setVisible(false);
        
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnldashboard = new javax.swing.JPanel();
        lbllogo = new javax.swing.JLabel();
        lblsublogo = new javax.swing.JLabel();
        lblborder = new javax.swing.JLabel();
        pnlhome = new javax.swing.JPanel();
        iconhome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlhospital = new javax.swing.JPanel();
        iconhospitals = new javax.swing.JLabel();
        lblhospitals = new javax.swing.JLabel();
        pnlplan = new javax.swing.JPanel();
        iconplan = new javax.swing.JLabel();
        lblplan = new javax.swing.JLabel();
        pnlregistration = new javax.swing.JPanel();
        iconregistration = new javax.swing.JLabel();
        lblregistration = new javax.swing.JLabel();
        pnllogout = new javax.swing.JPanel();
        iconlogout = new javax.swing.JLabel();
        lbllogout = new javax.swing.JLabel();
        pnlback = new javax.swing.JPanel();
        backicon = new javax.swing.JLabel();
        lblbottom = new javax.swing.JLabel();
        pnlforward = new javax.swing.JPanel();
        lblforward = new javax.swing.JLabel();
        pnlrent = new javax.swing.JPanel();
        iconrent1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        iconlogo = new javax.swing.JLabel();
        pnlhead = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        district = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        searchbt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultArea = new javax.swing.JTextArea();
        clearbt = new javax.swing.JButton();
        backimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnldashboard.setBackground(new java.awt.Color(54, 33, 89));
        pnldashboard.setPreferredSize(new java.awt.Dimension(310, 600));

        lbllogo.setBackground(new java.awt.Color(25, 151, 148));
        lbllogo.setFont(new java.awt.Font("Source Code Pro Black", 1, 28)); // NOI18N
        lbllogo.setForeground(new java.awt.Color(255, 255, 255));
        lbllogo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbllogo.setText("HOLIDAY HELPER...");

        lblsublogo.setBackground(new java.awt.Color(25, 151, 148));
        lblsublogo.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 18)); // NOI18N
        lblsublogo.setForeground(new java.awt.Color(255, 255, 255));
        lblsublogo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblsublogo.setText("--FLY SRILANKA--");

        lblborder.setBackground(new java.awt.Color(255, 255, 255));
        lblborder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblborder.setPreferredSize(new java.awt.Dimension(2, 2));

        pnlhome.setBackground(new java.awt.Color(85, 65, 118));
        pnlhome.setForeground(new java.awt.Color(255, 255, 255));
        pnlhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlhomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlhomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlhomeMousePressed(evt);
            }
        });
        pnlhome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconhome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hospital/Photos/home.png"))); // NOI18N
        pnlhome.add(iconhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 50));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Home");
        pnlhome.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 170, 30));

        pnlhospital.setBackground(new java.awt.Color(64, 43, 100));
        pnlhospital.setForeground(new java.awt.Color(255, 255, 255));
        pnlhospital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlhospitalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlhospitalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlhospitalMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlhospitalMousePressed(evt);
            }
        });
        pnlhospital.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconhospitals.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconhospitals.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hospital/Photos/hospitals.png"))); // NOI18N
        pnlhospital.add(iconhospitals, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 50));

        lblhospitals.setBackground(new java.awt.Color(255, 255, 255));
        lblhospitals.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblhospitals.setForeground(new java.awt.Color(255, 255, 255));
        lblhospitals.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblhospitals.setText("Hospitals");
        pnlhospital.add(lblhospitals, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 170, 30));

        pnlplan.setBackground(new java.awt.Color(64, 43, 100));
        pnlplan.setForeground(new java.awt.Color(255, 255, 255));
        pnlplan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlplanMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlplanMousePressed(evt);
            }
        });
        pnlplan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconplan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconplan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hospital/Photos/plan.png"))); // NOI18N
        pnlplan.add(iconplan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 40));

        lblplan.setBackground(new java.awt.Color(255, 255, 255));
        lblplan.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblplan.setForeground(new java.awt.Color(255, 255, 255));
        lblplan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblplan.setText("Make My Plan");
        pnlplan.add(lblplan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 170, 30));

        pnlregistration.setBackground(new java.awt.Color(64, 43, 100));
        pnlregistration.setForeground(new java.awt.Color(255, 255, 255));
        pnlregistration.setPreferredSize(new java.awt.Dimension(270, 50));
        pnlregistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlregistrationMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlregistrationMousePressed(evt);
            }
        });
        pnlregistration.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconregistration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconregistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hospital/Photos/registration.png"))); // NOI18N
        pnlregistration.add(iconregistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 30));

        lblregistration.setBackground(new java.awt.Color(255, 255, 255));
        lblregistration.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblregistration.setForeground(new java.awt.Color(255, 255, 255));
        lblregistration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblregistration.setText("Registration");
        pnlregistration.add(lblregistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 170, 20));

        pnllogout.setBackground(new java.awt.Color(64, 43, 100));
        pnllogout.setForeground(new java.awt.Color(255, 255, 255));
        pnllogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnllogoutMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnllogoutMousePressed(evt);
            }
        });
        pnllogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconlogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hospital/Photos/logout.png"))); // NOI18N
        pnllogout.add(iconlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 40));

        lbllogout.setBackground(new java.awt.Color(255, 255, 255));
        lbllogout.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbllogout.setForeground(new java.awt.Color(255, 255, 255));
        lbllogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllogout.setText("Log Out");
        lbllogout.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnllogout.add(lbllogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 170, 30));

        pnlback.setBackground(new java.awt.Color(64, 43, 100));
        pnlback.setForeground(new java.awt.Color(255, 255, 255));
        pnlback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlbackMousePressed(evt);
            }
        });
        pnlback.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backicon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hospital/Photos/back.png"))); // NOI18N
        pnlback.add(backicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, -1));
        backicon.getAccessibleContext().setAccessibleParent(this);

        lblbottom.setBackground(new java.awt.Color(255, 255, 255));
        lblbottom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblbottom.setPreferredSize(new java.awt.Dimension(2, 2));

        pnlforward.setBackground(new java.awt.Color(64, 43, 100));
        pnlforward.setForeground(new java.awt.Color(255, 255, 255));
        pnlforward.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlforwardMousePressed(evt);
            }
        });
        pnlforward.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblforward.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblforward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hospital/Photos/forward.png"))); // NOI18N
        pnlforward.add(lblforward, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 60, -1));

        pnlrent.setBackground(new java.awt.Color(64, 43, 100));
        pnlrent.setForeground(new java.awt.Color(255, 255, 255));
        pnlrent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlrentMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlrentMousePressed(evt);
            }
        });
        pnlrent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconrent1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconrent1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hospital/Photos/rent.png"))); // NOI18N
        pnlrent.add(iconrent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 40));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Rent Vehicles");
        pnlrent.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 170, 30));

        iconlogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hospital/Photos/travel.png"))); // NOI18N

        javax.swing.GroupLayout pnldashboardLayout = new javax.swing.GroupLayout(pnldashboard);
        pnldashboard.setLayout(pnldashboardLayout);
        pnldashboardLayout.setHorizontalGroup(
            pnldashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlhome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlhospital, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnllogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlplan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlregistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlrent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnldashboardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblsublogo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(pnldashboardLayout.createSequentialGroup()
                .addGroup(pnldashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnldashboardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnldashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbllogo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconlogo)))
                    .addComponent(lblbottom, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnldashboardLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblborder, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnldashboardLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pnlback, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlforward, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        pnldashboardLayout.setVerticalGroup(
            pnldashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbllogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblsublogo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblborder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnldashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnldashboardLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(pnlhome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(pnlhospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(pnlrent, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(pnlregistration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(pnlplan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnllogout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnldashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnldashboardLayout.createSequentialGroup()
                                .addComponent(lblbottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67))
                            .addComponent(pnlforward, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnldashboardLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlback, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(150, 150, 150))
        );

        pnlhead.setBackground(new java.awt.Color(160, 161, 194));
        pnlhead.setPreferredSize(new java.awt.Dimension(1240, 170));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hospitals in Sri Lanka");

        javax.swing.GroupLayout pnlheadLayout = new javax.swing.GroupLayout(pnlhead);
        pnlhead.setLayout(pnlheadLayout);
        pnlheadLayout.setHorizontalGroup(
            pnlheadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlheadLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(441, Short.MAX_VALUE))
        );
        pnlheadLayout.setVerticalGroup(
            pnlheadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlheadLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        district.setBackground(new java.awt.Color(204, 204, 255));
        district.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        district.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select District", "Colombo", "Kandy", "Matara", "Jaffna", "Polonnaruwa", "Mullaitivu", "Kurunegala", "Kandy", "Kalutara", "Gampaha", "Anuradhapura", "Nuwara Eliya", "Badulla", "Batticaloa", "Matale", "Mannar", "Galle", "Trincomalee", "Ratnapura", "Hambantota", "Ampara", "Puttalam", "Kilinochchi", "Monaragala", "Vavuniya" }));
        district.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                districtActionPerformed(evt);
            }
        });
        panel.add(district, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 470, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hospital/Photos/searchbt.png"))); // NOI18N
        panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 30, 40));

        searchbt.setBackground(new java.awt.Color(0, 153, 204));
        searchbt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchbt.setText("Search");
        searchbt.setBorder(null);
        searchbt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchbt.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                searchbtMouseDragged(evt);
            }
        });
        searchbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtActionPerformed(evt);
            }
        });
        searchbt.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                searchbtPropertyChange(evt);
            }
        });
        panel.add(searchbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 90, 40));

        resultArea.setColumns(20);
        resultArea.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        resultArea.setForeground(new java.awt.Color(51, 51, 255));
        resultArea.setRows(5);
        resultArea.setToolTipText("");
        resultArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 5));
        jScrollPane1.setViewportView(resultArea);

        panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 420, 390));

        clearbt.setForeground(new java.awt.Color(51, 0, 255));
        clearbt.setText("Clear");
        clearbt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtActionPerformed(evt);
            }
        });
        panel.add(clearbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 520, -1, -1));

        backimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hospital/Photos/Untitled-1.jpg"))); // NOI18N
        backimg.setText("jLabel3");
        panel.add(backimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 1320, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnldashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlhead, javax.swing.GroupLayout.PREFERRED_SIZE, 1320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlhead, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnldashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnlhospitalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlhospitalMousePressed
        // TODO add your handling code here:
         resetColor(pnlhome);
        resetColor(pnlback);
        resetColor(pnlforward);
        setColor(pnlhospital);
        resetColor(pnllogout);
        resetColor(pnlregistration);
        resetColor(pnlplan);
         resetColor(pnlrent);
    }//GEN-LAST:event_pnlhospitalMousePressed

    private void pnlhospitalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlhospitalMouseEntered
        // TODO add your handling code here:
        
       // setColor(pnlhospital);
    }//GEN-LAST:event_pnlhospitalMouseEntered

    private void pnlhospitalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlhospitalMouseExited
        // TODO add your handling code here:
       // resetColor(pnlhospital);
    }//GEN-LAST:event_pnlhospitalMouseExited

    private void pnlhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlhomeMouseClicked
        // TODO add your handling code here:
        
                Homepg H = new Homepg();
                H.setVisible(true);
                setVisible(false);
        
    }//GEN-LAST:event_pnlhomeMouseClicked

    private void pnlhospitalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlhospitalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlhospitalMouseClicked

    private void pnlplanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlplanMousePressed
        // TODO add your handling code here:
        resetColor(pnlhome);
        resetColor(pnlback);
        resetColor(pnlforward);
        resetColor(pnlhospital);
        resetColor(pnllogout);
        resetColor(pnlregistration);
        resetColor(pnlplan);
        setColor(pnlplan);
         resetColor(pnlrent);
    }//GEN-LAST:event_pnlplanMousePressed

    private void pnlregistrationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlregistrationMousePressed
        // TODO add your handling code here:
        resetColor(pnlhome);
        resetColor(pnlback);
        resetColor(pnlforward);
        resetColor(pnlhospital);
        resetColor(pnllogout);
        setColor(pnlregistration);
        resetColor(pnlplan);
        resetColor(pnlrent);
        
       // frameplan.setVisible(true);
    }//GEN-LAST:event_pnlregistrationMousePressed

    private void pnllogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnllogoutMousePressed
        // TODO add your handling code here:
        resetColor(pnlhome);
        resetColor(pnlback);
        resetColor(pnlforward);
        resetColor(pnlhospital);
        setColor(pnllogout);
        resetColor(pnlregistration);
        resetColor(pnlplan);
        resetColor(pnlrent);
    }//GEN-LAST:event_pnllogoutMousePressed

    private void pnlrentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlrentMousePressed
        // TODO add your handling code here:
        resetColor(pnlhome);
        resetColor(pnlback);
        resetColor(pnlforward);
        resetColor(pnlhospital);
        resetColor(pnllogout);
        resetColor(pnlregistration);
        resetColor(pnlplan);
        setColor(pnlrent);
    }//GEN-LAST:event_pnlrentMousePressed

    private void pnlbackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlbackMousePressed
        // TODO add your handling code here:
        resetColor(pnlhome);
        setColor(pnlback);
        resetColor(pnlforward);
        resetColor(pnlhospital);
        resetColor(pnllogout);
        resetColor(pnlregistration);
        resetColor(pnlplan);
        resetColor(pnlrent);
    }//GEN-LAST:event_pnlbackMousePressed

    private void pnlforwardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlforwardMousePressed
        // TODO add your handling code here:
        resetColor(pnlhome);
        resetColor(pnlback);
        setColor(pnlforward);
        resetColor(pnlhospital);
        resetColor(pnllogout);
        resetColor(pnlregistration);
        resetColor(pnlplan);
        resetColor(pnlrent);
    }//GEN-LAST:event_pnlforwardMousePressed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnnextActionPerformed

    private void txtcalanderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcalanderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcalanderMouseClicked

    private void txtcalanderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcalanderKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcalanderKeyPressed

    private void pnlhomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlhomeMousePressed
        // TODO add your handling code here:
        setColor(pnlhome);
        resetColor(pnlback);
        resetColor(pnlforward);
        resetColor(pnlhospital);
        resetColor(pnllogout);
        resetColor(pnlregistration);
        resetColor(pnlplan);
        resetColor(pnlrent);
    }//GEN-LAST:event_pnlhomeMousePressed

    private void pnlhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlhomeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlhomeMouseEntered

    private void pnlhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlhomeMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlhomeMouseExited

    private void searchbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtActionPerformed

            
           searchbt.addActionListener(e -> {
            // get the selected district from the combo box
            String selectedDistrict = (String) district.getSelectedItem();
            
            // query the database to get the hospitals in the selected district
            try {
                
                DbConnection l = new DbConnection();
                
                // create a connection to the database
                Class.forName(l.getDrive_class());
                Connection conn = DriverManager.getConnection(l.getUrl(), l.getUsername(), l.getPassword());
                
                // create a statement to execute the query
                Statement stmt = conn.createStatement();
                
                // execute the query and get the result set
                ResultSet rs = stmt.executeQuery("SELECT * FROM medicaltb WHERE district = '" + selectedDistrict + "'");
                
                // display the result in the text area
                resultArea.setText("");
                while (rs.next()) {
                    String hospitalName = rs.getString("name");
                    String hospitalAddress = rs.getString("address");
                    String hospitalno=rs.getString("tel_no");
                    resultArea.append("\n"+hospitalName + "\n" + hospitalAddress + "\n" +hospitalno+"\n");
                }
                resultArea.setVisible(true);
                clearbt.setVisible(true);
                
                // close the result set, statement, and connection
                rs.close();
                stmt.close();
                conn.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }  catch (ClassNotFoundException ex) {
                   Logger.getLogger(myplan1.class.getName()).log(Level.SEVERE, null, ex);
               }
        });
    
    }//GEN-LAST:event_searchbtActionPerformed

    private void searchbtMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbtMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_searchbtMouseDragged

    private void searchbtPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_searchbtPropertyChange
        
    }//GEN-LAST:event_searchbtPropertyChange

    private void districtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_districtActionPerformed

       
    }//GEN-LAST:event_districtActionPerformed

    private void clearbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtActionPerformed
 resultArea.setText("");
 // TODO add your handling code here:
    }//GEN-LAST:event_clearbtActionPerformed

    private void pnlregistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlregistrationMouseClicked
        // TODO add your handling code here:
        
            SignUp obj = new SignUp();
                obj.setVisible(true);
                setVisible(false);
    }//GEN-LAST:event_pnlregistrationMouseClicked

    private void pnlrentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlrentMouseClicked
        // TODO add your handling code here:
        Rent1 obj = new Rent1();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_pnlrentMouseClicked

    private void pnlplanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlplanMouseClicked
        // TODO add your handling code here:
        myplan obj = new myplan();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_pnlplanMouseClicked

    private void pnllogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnllogoutMouseClicked
        // TODO add your handling code here:
        
         Login1 obj =new Login1();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_pnllogoutMouseClicked

    public void setColor(JPanel panel)
    {
        panel.setBackground(new Color(85,65,118));
        
    }
    public void resetColor(JPanel panel)
    {
        panel.setBackground(new Color(64,43,100));
    }
    
  
   

    
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        
        java.awt.EventQueue.invokeLater(() ->{
            new myplan1().setVisible(true);
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backicon;
    private javax.swing.JLabel backimg;
    private javax.swing.JButton clearbt;
    private javax.swing.JComboBox<String> district;
    private javax.swing.JLabel iconhome;
    private javax.swing.JLabel iconhospitals;
    private javax.swing.JLabel iconlogo;
    private javax.swing.JLabel iconlogout;
    private javax.swing.JLabel iconplan;
    private javax.swing.JLabel iconregistration;
    private javax.swing.JLabel iconrent1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblborder;
    private javax.swing.JLabel lblbottom;
    private javax.swing.JLabel lblforward;
    private javax.swing.JLabel lblhospitals;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JLabel lbllogout;
    private javax.swing.JLabel lblplan;
    private javax.swing.JLabel lblregistration;
    private javax.swing.JLabel lblsublogo;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel pnlback;
    private javax.swing.JPanel pnldashboard;
    private javax.swing.JPanel pnlforward;
    private javax.swing.JPanel pnlhead;
    private javax.swing.JPanel pnlhome;
    private javax.swing.JPanel pnlhospital;
    private javax.swing.JPanel pnllogout;
    private javax.swing.JPanel pnlplan;
    private javax.swing.JPanel pnlregistration;
    private javax.swing.JPanel pnlrent;
    private javax.swing.JTextArea resultArea;
    private javax.swing.JButton searchbt;
    // End of variables declaration//GEN-END:variables

    
}
